[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "@openzeppelin/contracts=node_modules/@openzeppelin/contracts/",
    "@layerzerolabs/solidity-examples=node_modules/@layerzerolabs/solidity-examples/"
]
